feat!: update tooling and ci (#12)
* feat: introduce ruff to replace flake8 and isort

* fix: appease ruff in scripts

* feat: update pre-commit

* feat: update ci

* fix(ci): actually use brain for once

* fix(ci): hope and cope

* fix(ci): wow

* fix(ci): i love ci

* fix(ci): hopefully the final fix now

* chore: document breaking change

* feat(ci): introduce skip-duplicate-actions

* refactor(ci): maybe try a little disnake theft

* fix(ci): maybe perhaps mayhaps perchance

* revert(ci): back to skip-duplicate-checks we go

* feat(ci): only run ci for specific pushes

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,84 +1,106 @@
-name: Lint and Test
+name: lint
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - "master"
+      - 'v[0-9]+.[0-9]+.x'  # matches to backport branches, e.g. v3.6
+      - "run-ci/"
+  pull_request:
 
 jobs:
+  # NOTE: We use skip-duplicate-actions instead of builtin concurrency rules as
+  #       the latter makes runs cancelled due to concurrency count as failed.
 
-  lint:
+  pre-install:
     runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v3
+    outputs:
+      should_skip: ${{ steps.skip_check.outputs.should_skip }}
 
-      - name: Setup Python 3.8
+    steps:
+      - id: skip_check
+        uses: fkirc/skip-duplicate-actions@v5
+        with:
+          concurrent_skipping: same_content_newer
+
+  install:
+    runs-on: ubuntu-latest
+
+    needs: pre-install
+    if: needs.pre-install.outputs.should_skip != 'true'
+
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Install poetry
+        uses: snok/install-poetry@v1
+
+      - name: Set up python
+        id: setup-python
         uses: actions/setup-python@v4
         with:
           python-version: 3.8
-
-      - name: Install Poetry
-        uses: snok/install-poetry@v1
+          cache: poetry
 
       - name: Install dependencies
         run: poetry install
 
-      - name: Lint
-        run: |
-          poetry run black src/disnake/ext/plugins examples --check
-          poetry run isort src/disnake/ext/plugins examples -c
-          poetry run flake8 src/disnake/ext/plugins examples
-
-  # test:
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-latest, macos-latest, windows-latest]
-  #       python-version: ["3.8", "3.9", "3.10"]
-
-  #   runs-on: ${{ matrix.os }}
-
-  #   steps:
-  #     - uses: actions/checkout@v3
-
-  #     - name: Setup Python ${{ matrix.python-version }}
-  #       uses: actions/setup-python@v4
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
-
-  #     - name: Install poetry
-  #       run: |
-  #         python -m pip install poetry~=1.1.14
-
-  #     - name: Install dependencies
-  #       run: |
-  #         poetry install
-
-  #     - name: Run tests
-  #       run: |
-  #         python -m pytest
+      - name: Update dependencies
+        run: poetry update
 
   pyright:
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.8", "3.9", "3.10"]
-
     runs-on: ubuntu-latest
 
+    needs: install
+
+    strategy:
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
+      fail-fast: false
+
     steps:
-      - uses: actions/checkout@v3
+      - name: Check out repository
+        uses: actions/checkout@v3
 
-      - name: Setup Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Install Poetry
+      - name: Install poetry
         uses: snok/install-poetry@v1
 
-      - name: Install requirements
-        run: |
-          poetry install
+      - name: Set up python
+        id: setup-python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+          cache: poetry
 
+      # We should have the cached venv from the install job here.
       - name: Run pyright
-        run: |
-          poetry run pyright
+        run: poetry run pyright --pythonversion ${{ matrix.python-version }}
+
+  lint:
+    runs-on: ubuntu-latest
+
+    needs: install
+
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Install poetry
+        uses: snok/install-poetry@v1
+
+      - name: Set up python
+        id: setup-python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+          cache: poetry
+
+      # We should have the cached venv from the install job here.
+      - name: Run ruff
+        run: poetry run ruff .
+
+      - name: Run slotscheck
+        if: success() || failure()
+        run: poetry run dev-symlink & poetry run slotscheck -m disnake.ext.plugins
